config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  resources :categories
  resources :posts
  resources :messages
  root "categories#index"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
         

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts, dependent: :destroy
    validates :name, presence: true

    def self.ransackable_attributes(auth_object = nil)
        %w[id name created_at updated_at] 
    end
    
    def self.ransackable_associations(auth_object = nil)
        %w[posts]
    end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, presence: true

  def self.ransackable_attributes(auth_object = nil)
    %w[id content user_id post_id created_at updated_at]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[post user]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :messages, dependent: :destroy
  has_many_attached :images
  
  validates :title, presence: true
  validates :description, presence: true
  validates :category, presence: true

  def self.ransackable_associations(auth_object = nil)
    %w[user category messages]
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[id title description created_at updated_at user_id category_id]  
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true

  has_many :posts, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_one_attached :profile_image

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "name", "username", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!

    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username, :profile_image])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  def index
    @messages = Message.all
  end

  def show
  end

  def new
    @message = Message.new
  end

  def create
    @message = current_user.messages.build(message_params)
    if @message.save
      redirect_to @message, notice: 'Message was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @message.update(message_params)
      redirect_to @message, notice: 'Message was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @message.destroy
    redirect_to messages_url, notice: 'Message was successfully destroyed.'
  end

  private

  def set_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:content, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :category_id, :user_id, images: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/edit.html.erb
<%= form_with(model: @category, local: true) do |form| %>
    <div class="field">
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/categories/index.html.erb
<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td>
          <%= link_to 'Show', category_path(category) %>
          <%= link_to 'Edit', edit_category_path(category) %>
          <%= link_to 'Destroy', category_path(category), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<%= form_with(model: @category, local: true) do |form| %>
    <div class="field">
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/categories/show.html.erb
<h1>Category: <%= @category.name %></h1>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adminapplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/edit.html.erb
<%= form_with(model: @message, local: true) do |form| %>
    <div class="field">
      <%= form.label :content %><br>
      <%= form.text_area :content %>
    </div>
  
    <div class="field">
      <%= form.label :post %><br>
      <%= form.collection_select :post_id, Post.all, :id, :title %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/messages/index.html.erb
<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Post</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.content %></td>
        <td><%= message.post.title %></td>
        <td>
          <%= link_to 'Show', message_path(message) %>
          <%= link_to 'Edit', edit_message_path(message) %>
          <%= link_to 'Destroy', message_path(message), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<%= form_with(model: @message, local: true) do |form| %>
    <div class="field">
      <%= form.label :content %><br>
      <%= form.text_area :content %>
    </div>
  
    <div class="field">
      <%= form.label :post %><br>
      <%= form.collection_select :post_id, Post.all, :id, :title %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/messages/show.html.erb
<h1>Message for Post: <%= @message.post.title %></h1>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/posts/edit.html.erb
<%= form_with(model: @post, local: true) do |form| %>
    <div class="field">
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </div>
  
    <div class="field">
      <%= form.label :description %><br>
      <%= form.text_area :description %>
    </div>
  
    <div class="field">
      <%= form.label :category %><br>
      <%= form.collection_select :category_id, Category.all, :id, :name %>
    </div>
  
    <div class="field">
      <%= form.label :images %><br>
      <%= form.file_field :images, multiple: true %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>
  

app/views/posts/index.html.erb
<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Category</th>
      <th>User</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= post.category.name %></td>
        <td><%= post.user.username %></td>
        <td>
          <%= link_to 'Show', post_path(post) %>
          <%= link_to 'Edit', edit_post_path(post) %>
          <%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<%= form_with(model: @post, local: true) do |form| %>
    <div class="field">
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </div>
  
    <div class="field">
      <%= form.label :description %><br>
      <%= form.text_area :description %>
    </div>
  
    <div class="field">
      <%= form.label :category %><br>
      <%= form.collection_select :category_id, Category.all, :id, :name %>
    </div>
  
    <div class="field">
      <%= form.label :images %><br>
      <%= form.file_field :images, multiple: true %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>
  

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @post.category.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @post.user.username %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>